name: mongo-sharding

services:
  configSrv:
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: unless-stopped
    command:
      - mongod
      - --configsvr
      - --replSet
      - config_server
      - --bind_ip_all
      - --port
      - "27017"
    volumes:
      - config_data:/data/db
    networks:
      - mongo_network
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27017", "--quiet", "--eval", "quit(db.adminCommand({ ping: 1 }).ok ? 0 : 1)"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  shard1:
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: unless-stopped
    command:
      - mongod
      - --shardsvr
      - --replSet
      - shard1
      - --bind_ip_all
      - --port
      - "27018"
    volumes:
      - shard1_data:/data/db
    networks:
      - mongo_network
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27018", "--quiet", "--eval", "quit(db.adminCommand({ ping: 1 }).ok ? 0 : 1)"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  shard2:
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: unless-stopped
    command:
      - mongod
      - --shardsvr
      - --replSet
      - shard2
      - --bind_ip_all
      - --port
      - "27019"
    volumes:
      - shard2_data:/data/db
    networks:
      - mongo_network
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27019", "--quiet", "--eval", "quit(db.adminCommand({ ping: 1 }).ok ? 0 : 1)"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  mongos:
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: unless-stopped
    command:
      - mongos
      - --configdb
      - config_server/configSrv:27017
      - --bind_ip_all
      - --port
      - "27020"
    depends_on:
      - configSrv
      - shard1
      - shard2
    networks:
      - mongo_network
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27020", "--quiet", "--eval", "quit(db.adminCommand({ ping: 1 }).ok ? 0 : 1)"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s

  pymongo-api:
    build:
      context: ./api_app
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongos
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: mongodb://mongos:27020
      MONGODB_DATABASE_NAME: somedb
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  config_data:
  shard1_data:
  shard2_data:
